# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtWidgets
from PySide6.QtGui import QDesktopServices


class Ui_articleform(object):
    def setupUi(self, articleform):
        articleform.setObjectName("articleform")
        articleform.setWindowModality(QtCore.Qt.NonModal)
        articleform.resize(900, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(articleform.sizePolicy().hasHeightForWidth())
        articleform.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(articleform)
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowser = QtWidgets.QTextBrowser(articleform)
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.anchorClicked.connect(self.openExternalLink)
        self.gridLayout.addWidget(self.textBrowser, 0, 0, 1, 1)

        self.retranslateUi(articleform)
        QtCore.QMetaObject.connectSlotsByName(articleform)

    def openExternalLink(self, url):
        # Open the link in the system browser
        QDesktopServices.openUrl(url)

    def retranslateUi(self, articleform):
        _translate = QtCore.QCoreApplication.translate
        articleform.setWindowTitle(_translate("articleform", "帮助教程文章"))
        self.textBrowser.setHtml(_translate("articleform", """
        <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta name="qrichtext" content="1" />
<style type="text/css">
ul{margin-bottom:30px}
p, li { white-space: pre-wrap; margin-bottom:10px}
a{text-decoration:none;color:#fff;font-size:14px}
a:hover{color:#ff0}
</style></head>
<body style="font-size:9pt; font-weight:400; font-style:normal;">
<div>
<p style="font-size:18px;color:#fff">
请参考项目文档
</p>
</div>



<ul>

<li>使用方法</li>
<li>新手快速入门</li>
<li>模型使用与说明</li>
<li>界面选项与相关设置</li>
<li>多角色配音</li>
<li>试听配音</li>
<li>模型下载</li>
<li>常见问题</li>

<li>人声和背景音乐分离</li>
<li>CUDA安装配置</li>
<li>如何彻底删除缓存</li>
<li>频繁出现重试5次失败</li>
<li>百度翻译/腾讯翻译/Gemini等API申请</li>
<li>ChatGPT接口使用</li>
<li>部署DeepLX</li>
<li>在cloudflare上创建免费翻译API</li>
<li>FreeGoogle翻译使用</li>
<li>无需代理使用Google翻译的方法</li>
<li>部署OTT文字翻译</li>

<li>选项参数说明</li>
<li>声音字幕画面对齐方法</li>
<li>faster模式与openai模式的区别</li>
<li>提高翻译质量的技巧</li>
<li>CLI命令行使用</li>
<li>在软件中使用GPT-SoVITS配音</li>
<li>本地部署Qwen通义千问大模型</li>

</ul>

<p style="padding:8px;margin-top:15px;margin-bottom:20px">
<a style="color:#ff0;" href="about:blank">帮助与文档暂无</a></p>

<hr style="color:#161E26;background-color:#161E26">
<hr style="color:#161E26;background-color:#161E26">
</body></html>
"""))
